# Generated by Django 5.0 on 2023-12-06 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_blog_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['name']},
        ),
    ]
