# Generated by Django 5.0 on 2023-12-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_ordered_date_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='slug',
            field=models.SlugField(default='', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
