# Generated by Django 5.0 on 2023-12-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
