# Generated by Django 5.0 on 2024-01-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_ticket_ticket_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_key',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
