# Generated by Django 5.0 on 2023-12-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_shopper_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopper',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
